### ISSUE TITLE
Weird output in python after multiple requests

### ISSUE THREAD

**Issue by KevorkSulahian** [wastella/dalaipy#1]
Thanks for the code love it. 
I just ran into this issue when requesting multiple, where I get back all of the requests but somewhat merged.

Have you also ran into this? And also is there a way of just getting all of the outputs?

**Comment by wastella** [comment]
Yeah, I'm not  sure what happened, I think it might be because of the use of global variables, which doesnt support multi-threading, but I think it also might affect this, I'm currently refactoring the code to put the internal functions inside the class, hopefully that fixes it, if not I'll keep looking into it!

**Comment by wastella** [comment]
And, what do you mean by getting all of the outputs, you can get the dictionaries raw by putting prettify=False (look in the readme documentation).

**Comment by KevorkSulahian** [comment]
Sorry, I have a headache and my brain hurts sorry for not making sense. I meant to say that is there way to get all the prompts even older ones at the same time but looking at the code I see that It will be difficult. I will take a look at the dalai source tomorrow and see if I can figure something out, will update you if I do!

**Comment by wastella** [comment]
Definetly, feel free to make a PR if you find something!

**Comment by wastella** [comment]
So unfortunately, Dalai does not support concurent requests (multiple requests at the same time). But, I'm going to see what I can do about a queue system maybe, or sometihng like that to send them one at a time fast.

**Comment by wastella** [comment]
@KevorkSulahian would you want me to make a wrapper directly to llama.cpp, specifically to make programic requests fast, and support queing for multiple requests?

**Comment by KevorkSulahian** [comment]
That would be perfect

**Comment by wastella** [comment]
It will take a little bit of time, as my C is rusty, but I'll work on it!

**Comment by wastella** [comment]
After some research, I think the best way to use python with llama and alpaca would be https://github.com/PotatoSpudowski/fastLLaMa. Im going to test it right now to see how it handles multiple requests at once!

**Comment by wastella** [comment]
nvm i cant even git it working, ima just keep updating this project!

**Comment by wastella** [comment]
@KevorkSulahian Can you build from source from github and try it now, I think it should work! Please let me know!

**Comment by PotatoSpudowski** [comment]
Hi, 
Sorry to hear that fastLLaMa did not work before. We have updated a few things in the feature/refactor branch. Gimme a few days till we can test it out properly and I will get back to you. 

Also love the project!

**Comment by wastella** [comment]
Honestly its probably because I didnt install it right. And thanks so much for the support!

**Comment by PotatoSpudowski** [comment]
Yeah we were using pybind11 for creating the bindings before. It was a huge bottleneck. We moved away and are now using shared libraries. Should work with any python version and should be easier to add more language support 👀
So much simpler now. Also we have a setup.py file now which simplified everything.
